name: CI (Arch) (appimage)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson rust cargo clang glslang libcap wlroots0.18 sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres libxtst libxkbcommon libdrm libinput wayland-protocols benchmark xorg-xwayland pipewire cmake libavif libheif aom rav1e libdecor libxdamage luajit libva libxss wget curl xorg-server-xvfb fuse-overlayfs bubblewrap libxkbcommon zsync pipewire pulseaudio pipewire-audio alsa-plugins libxkbcommon-x11 libvdpau libvdpau-va-gl sudo pkg-config openssl zip

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build partydeck
        run: cargo build --release -F build_gamescope -F download_deps

      - name: Build appimage
        run: |
          ./dist/build_appimage.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: |
            ./dist/appimage_generated/partydeck-anylinux-x86_64.AppImage
