name: CI Build

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  BUILD_NAME:
    ${{ github.event.pull_request.number && format('build-pr-{0}', github.event.pull_request.number) || format('build-patch-{0}', github.sha) }}

jobs:
  build-base:
    runs-on: ubuntu-latest
    container: ghcr.io/steamdeckhomebrew/holo-toolchain-rust@sha256:818de45e147f35798c66498380b31bd1fe8bf75afdf0a22b027053706836faf1

    steps:
      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-cache-STEAMOS

      - name: Install dependencies
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm --needed \
              git meson clang glslang libcap sdl2 vulkan-headers \
              libx11 libxmu libxcomposite libxrender libxres libxtst libxkbcommon \
              libdrm libinput wayland-protocols benchmark xorg-xwayland pipewire \
              lcms2 hwdata seatd xcb-util-wm xcb-util-errors \
              cmake libavif libheif aom rav1e libdecor libxdamage luajit libva \
              libxss wget curl xorg-server-xvfb fuse-overlayfs bubblewrap zsync \
              pulseaudio pipewire-audio alsa-plugins libxkbcommon-x11 libvdpau \
              libvdpau-va-gl sudo pkgconf openssl zip base-devel \
          && pacman -S --noconfirm --overwrite '*' libpipewire \
          && yes | pacman -Scc

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cargo cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build partydeck
        run: |
          export BUILD_NAME="partydeck-CI"
          ./dist/build_dist.sh
          mv ./dist/build_generated/partydeck-CI/release partydeck

      - name: Create tarball
        run: tar -czf "partydeck-UNOFFICIAL-linux-x86_64.tar.gz" partydeck/

      - name: Upload base executable
        uses: actions/upload-artifact@v4
        with:
          name: partydeck-UNOFFICIAL-CI-raw-only-${{ env.BUILD_NAME }}
          path: partydeck-UNOFFICIAL-linux-x86_64.tar.gz

  build-appimage:
    needs: build-base
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-cache-ARCH

      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed \
            git meson rust cargo clang glslang libcap wlroots0.18 sdl2 \
            vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake libavif libheif aom rav1e libdecor libxdamage \
            luajit libva libxss wget curl xorg-server-xvfb fuse-overlayfs bubblewrap \
            libxkbcommon zsync pipewire pulseaudio pipewire-audio alsa-plugins \
            libxkbcommon-x11 libvdpau libvdpau-va-gl sudo pkg-config openssl zip libdisplay-info

      - uses: actions/checkout@v4

      - name: Download base executable
        uses: actions/download-artifact@v4
        with:
          name: partydeck-UNOFFICIAL-CI-raw-only-${{ env.BUILD_NAME }}

      - name: Extract base build
        run: tar -xzf partydeck-UNOFFICIAL-linux-x86_64.tar.gz

      - name: Build appimage
        run: |
          ln -s /usr/lib/libdisplay-info.so /usr/lib/libdisplay-info.so.2 || true
          export RELEASE_BUNDLE_DIR=../../partydeck
          ./dist/build_appimage.sh
          cp ./dist/appimage_generated/partydeck-anylinux-x86_64.AppImage partydeck-UNOFFICIAL-anylinux-x86_64.AppImage

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: partydeck-UNOFFICIAL-CI-full-${{ env.BUILD_NAME }}
          path: |
            partydeck-UNOFFICIAL-linux-x86_64.tar.gz
            partydeck-UNOFFICIAL-anylinux-x86_64.AppImage
