name: CI (Arch) (appimage)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Appimage
        run: |
          docker build \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            -t partydeck-appimage-build \
            -f dist/Dockerfile.appimage .

      - name: Build release skeleton
        run: 
          docker run --rm -v "$PWD:/workspace" partydeck-appimage-build

      - name: Rename and move release
        run:
          mv ./dist/appimage_generated/partydeck-anylinux-x86_64.AppImage partydeck-UNOFFICIAL-anylinux-x86_64.AppImage

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: built-UNOFFICIAL-appimage
          path: |
            partydeck-UNOFFICIAL-anylinux-x86_64.AppImage